services:
  db:
    image: mysql:8.0
    container_name: mysql_identity_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: apiweb
    ports:
      - "3307:3306"
    volumes:
      - db_data_identity:/var/lib/mysql

  app:
    build: .
    container_name: php_identity_service
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

volumes:
  db_data_identity: